# Generated by Django 2.1.1 on 2021-09-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, unique=True)),
                ('fullname2', models.CharField(blank=True, max_length=50, unique=True)),
                ('iiserid', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('lvl', models.IntegerField(default=1)),
            ],
        ),
    ]
