# Generated by Django 2.1.1 on 2021-09-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehunt', '0002_globalvariables'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='log',
            field=models.BooleanField(default=False),
        ),
    ]
