# Generated by Django 2.1.1 on 2021-10-24 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehunt', '0010_auto_20211024_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvariables',
            name='test_dur',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
