# Generated by Django 2.1.1 on 2021-10-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehunt', '0012_auto_20211024_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvariables',
            name='test_dur',
            field=models.DurationField(),
        ),
    ]
