# Generated by Django 2.1.1 on 2021-10-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehunt', '0013_auto_20211024_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvariables',
            name='test_dur',
            field=models.DurationField(default='1:00:00'),
        ),
    ]
