# Generated by Django 2.1.1 on 2021-09-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehunt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='iiserid',
            field=models.TextField(default='parth.gupte@students.iiserpune.ac.in', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
