# Generated by Django 2.1.1 on 2021-09-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehunt', '0002_auto_20210904_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname2',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
