# Generated by Django 2.1.1 on 2021-09-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehunt', '0006_auto_20210907_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('lvl', models.IntegerField(primary_key=True, serialize=False)),
                ('imgpath', models.TextField()),
                ('question', models.TextField()),
                ('modelanswer', models.TextField()),
            ],
        ),
    ]
