# Generated by Django 2.1.1 on 2021-09-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehunt', '0007_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='lastlvl_time',
            field=models.DateTimeField(default='2021-09-08 00:00:00'),
        ),
    ]
