# Generated by Django 2.1.1 on 2021-09-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehunt', '0008_users_lastlvl_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='fullname2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
