# Generated by Django 3.2.9 on 2021-12-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehunt', '0009_auto_20210909_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='fullname2',
        ),
        migrations.AddField(
            model_name='users',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='iiserid',
            field=models.EmailField(max_length=70),
        ),
    ]
